services:
  api:
    build: .
    image: horuseye/vuln-service
    command: flask run --host=0.0.0.0 --port=8081
    ports:
      - "8081:8081"
    volumes:
      - ./outputs:/app/outputs
      - ./gcloud-credentials.json:/app/gcloud-credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-credentials.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: .
    image: horuseye/vuln-service
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./outputs:/app/outputs
      - ./gcloud-credentials.json:/app/gcloud-credentials.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-credentials.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

